PINECONE_API_KEY = "e3bb9b88-936e-41e3-91a5-47bc14257395"
PINECONE_ENVIRONMENT = "gcp-starter"
AZURE_OPENAI_KEY = "64e7c187bf824fb6a1ed25d889592335"
AZURE_OPENAI_ENDPOINT = "https://ragembedding.openai.azure.com/"
OPENAI_API_VERSION = "2023-12-01-preview"